---
title: "4.2 Consequences and Sources of Monopoly - Readings"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

# Recommended

- <i class="fas fas fa-book"></i> Ch. 9-1 in @textbook

- [<i class="fas fa-file-pdf"></i> Tullock (1967), "The Welfare Cost of Tariffs, Monopolies, and Theft"](/readings/Tullock-1967.pdf)
- [<i class="fas fa-file-pdf"></i> Kreuger (1974), "The Political Economy of the Rent-Seeking Society"](/readings/Kreuger-1974.pdf)
- [<i class="fas fa-file-pdf"></i> Mitchell (2012), "The Pathology of Privilege"](/readings/Mitchell-2012.pdf)
- [<i class="fas fa-file-pdf"></i> Theil (2014), "Competition is for Losers"](/readings/Theil-2014.pdf)
- [<i class="fas fa-podcast"></i> *NPR Planet Money* 599: "Why its Illegal to Braid Hair without a License"](https://www.npr.org/sections/money/2012/06/22/155596305/episode-381-why-its-illegal-to-braid-hair-without-a-license)
- [<i class="fas fa-podcast"></i> Freakonomics*: "Apple vs. Samsung: Who Owns the Rectangle?"](http://freakonomics.com/2012/08/03/apple-vs-samsung-who-owns-the-rectangle/))

Tullock (1967) is the famous paper that first describes the idea of "rent-seeking," though he did not come up with the term, that comes from Kreuger (1974). Tullock is very readable, and shows the connections between monopoly, tariffs, and theft in terms of the rents and the rent-seeking they create. Kreuger (1974) considers rent-seeking at a national level in terms of how it harms trade and development.

Mitchell (2012) is a readable collection of many ways that business and special interests rent-seek and convince governments to erect barriers to entry at the expense of competition and consumers, e.g. monopoly status, favorable regulations, subsidies, bailouts, loan guarantees, targeted tax breaks, protection from foreign competition, and noncompetitive contracts.

Theil (2014) is a provocative Op-ed^[Don't let the title fool you. This was written well before the politics of 2016!] in the Wall Street Journal that is actually an excerpt from his book *Zero to One: Notes on Startups, or How to Build the Future*^[Which I often teach with in in Industrial Organization.]. Theil argues that it is a poor business idea to compete in a competitive market, and for a business to be successful, it needs to be the *last*-mover in a market, such that it acts as a monopoly. If the market is still competitive and dynamic, the quest for monopoly power can have benefits to consumers in terms of creativity and innnovation (think Google, etc), since they do not have to worry as much about competition.

