---
title: "4.3: Pricing with Market Power - Practice Problems"
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(pander)
source(file.path(here::here(), "lib", "graphics.R"))
```

- [<i class="fas fa-file-pdf"></i> `Download as PDF`](/practice/20-practice.pdf)
- [<i class="fas fa-file-pdf"></i> `Answer Key`](/practice/20-practice-answers.pdf)

Promoters of a major college basketball tournament estimate that the demand for tickets for *adults* and by *students* are given by:

$$\begin{align*}
q_a&=5,000-10p_a\\
q_s&=10,000-100p_s\\
\end{align*}$$

> where $a$ represents adults and $s$ represents students. They estimate that the marginal and average total cost of seating an additional spectator is constant at $10.

## Question 1
The promoters wish to segment the market and charge adults and students different prices.

### Part A
For each segment of the market, find the inverse demand function and marginal revenue function.

### Part B
Find the profit-maximizing quantity and price for each segment. 

### Part C
How much total profit would the tournament earn if they could price discriminate?

## Question 2
Now suppose they could not price discriminate, and were forced to charge the same price for all attendees.

### Part A
Find the total market demand function.

### Part B
Find the inverse demand function for the total market, and then the marginal revenue function. 

### Part C
Find the profit-maximizing quantity and price for the whole market. 

## Part D
How much total profit would the tournament earn if they could not price discriminate?

