---
output:
  pdf_document:
    includes:
      before_body: 306exam1cover.tex 
      #after_body: Metrics2018finalformulas.tex
    latex_engine: pdflatex #required for Fira Sans font to render properly 
header-includes:
  - \usepackage{tikz, pgfplots, booktabs}
class: "Microeconomic Analysis"
examnum: "Exam 1"
coursecode: "ECON 306"
semester: "Spring 2019"
section: "Section 1"
---

## True/False/Uncertain and \emph{Explain} (5 points each)

Choose any **four (4)** of the following questions. Indicate whether the following statements are **True**, **False**, or **Uncertain** (1 point), and give a short (2-3 sentences) **explanation** (4 points).

1. Emily just received a big promotion at her law firm, which comes with a 30\% pay raise. Since receiving this promotion, she has bought 15\% more gas than usual, and 40\% more food. For Emily, gas is a \emph{necessity good} and food is a \emph{luxury good}.  

\vspace{2in}

2. All else equal, we would expect a person travelling alone to have a *higher* price elasticity of demand for air travel than a family traveling together. 


\clearpage 

3. The graph below shows two indifference curves between two goods, $x$ and $y$. 
	
\begin{figure}[h!]\scriptsize 
		\centering 
					\begin{tikzpicture}[scale=.4]
			\draw[->] (0,0) -- (11,0) coordinate (x axis) node[right]{$x$};
 			\draw[->] (0,0) -- (0,11) coordinate (y axis) node[above]{$y$};
			\draw[ultra thick] (0,8)--node[above]{$u_2$}(8,0);
			\draw[ultra thick] (0,6)--node[above]{$u_1$}(6,0);
		\end{tikzpicture}
\end{figure}

Based on the graph, the *cross price elasticity* between $x$ and $y$ is *positive*.


\vspace{2in}

3. Based on the Engel curve for Uber rides below, Uber rides are always a normal good.

\begin{figure}[h!]
\centering 
		\begin{tikzpicture}[scale=.06]
			\draw[->] (0,0) -- (110,0) coordinate (x axis) node[right]{Uber Rides};
 			\draw[->] (0,0) -- (0,110) coordinate (y axis) node[above]{Income Per Week (\$)};
				\draw[xstep=10cm, ystep=10cm, black, dotted] (0,0) grid (100,100); 
				 				\foreach \x/\xtext in { 0,10, 20,..., 100} 
 					\draw (\x,1pt) -- (\x,-1pt) node[anchor=north] {$\xtext$};
				\foreach \y/\ytext in { 10,20,..., 100} 
					\draw (1pt,\y) -- (-1pt,\y) node[anchor=east] {$\ytext$};
			\draw[ultra thick] (0,0)--(20,30)--(70,40)--(60,60)--(20,80)--(10,100);
 		\end{tikzpicture}
\end{figure}
 

\clearpage


\vspace{2in}

5. The graph below shows two indifference curves between two objects, $X$ and $Y$. If the consumer enjoys a higher level of utility on $U_2$ than on $U_1$, then $X$ is a bad, $Y$ is a good.

\begin{figure}[h!]\scriptsize 
		\centering 
			\begin{tikzpicture}[scale=.4]
			\draw[->] (0,0) -- (11,0) coordinate (x axis) node[right]{X};
 			\draw[->] (0,0) -- (0,11) coordinate (y axis) node[above]{Y};
			\draw[ultra thick] (1,1) to[out=90, in=180] (10,10)node[right]{$U_1$};
			\draw[ultra thick, dotted] (3,1) to[out=90, in=180] (10,8)node[right]{$U_2$};
 		\end{tikzpicture}
	\end{figure}


\vspace{2in}

6. The graph below depicts a *fall* in the price of Fidget Spinners.

\begin{figure}[h!]
\centering 
\scriptsize
	\begin{tikzpicture} 
	\begin{axis}[%clip=false,
		axis lines=middle, 
		enlarge x limits={rel=0.1, upper},
		enlarge y limits={rel=0.1, upper},
		every axis y label/.style={at={(axis description cs:-0.2,0.5)},rotate=90,anchor=north},
		every axis x label/.style={at={(axis description cs:0.5,-0.1)},anchor=north},
	%legend pos=outer north east,
	xlabel=Fidget Spinners,
	ylabel=Oranges,
	shader=flat,
	xtick={0,10, 20,...,60},
	ytick={0,10,20,...,60},
	grid=major,
	ymin=0,
	xmin=0,
	ymax=60,
	xmax=60,
]
	\addplot[domain=0:60, samples=25, very thick]{150/(x)};
	\addplot[domain=0:60, samples=25, very thick]{150/(x)+15.5};
	\draw[very thick] (axis cs:0,30)--(axis cs:20,0);
	\draw[very thick, dashed] (axis cs:0,30)--(axis cs:60,8);
	\draw[very thick, dashed] (axis cs:0,15)--(axis cs:40,0);
	\draw[fill=black] (axis cs:10,15)circle(0.075cm);
	\draw[fill=black] (axis cs:20,7.5)circle(0.075cm);
	\draw[fill=black] (axis cs:17,24)circle(0.075cm);
\end{axis}
\end{tikzpicture}
\end{figure}

According to the graph, Fidget Spinners are a *normal* good. 

\vspace{2in}

\clearpage

## Short Answer (10 points each)

Choose any \textbf{three (3)} questions to answer concisely (2-3 sentences). If applicable, show all work and clearly label all graphs.

7. Consider four objects: $a$, $b$, $c$, and $d$. If a person's utility function over them is
$$u(a,b,c,d)=a*b-c$$
then what kind of object is $a$, $b$, $c$, and $d$, respectively?


\vspace{3in}

8. Explain verbally, and with a graph, the difference between a change in demand and a change in quantity demanded.

\clearpage

9. If we are drawing an indifference curve that includes a \emph{bad} on at least one axis, which \emph{assumption(s)} of indifference curves do we violate, and why?

\vspace{3in}

10. Ashkar has the following preferences over bundles of (apples, bananas):
$$(2,6) \sim (4,2) \succ (2,0) \sim (1,2)$$

Which of the following utility functions could describe his preferences? Explain why, briefly. 

i. $u(a,b) = 2a+b$
ii. $u(a,b) = 4ab$
iii. $u(a,b) = 6a+3b$
iv. $u(a,b) = a^{2} b^{2}$


\clearpage

## Problem (30 points)

Show all work. You may *not* earn full credit if you only write the answer, even if correct.

11. Suppose you can buy Drinks ($D$) and Wings ($W$) at a local bar.

a. Suppose you have a budget of \$120/month to spend, the price of a Drink is \$3.00, and the price of a plate of Wings is \$4.00. Write a *graphable* equation for the budget constraint, and graph it on the first graph below. (3 points)

b. Suppose you earn utility according to the function:
\vspace{-0.5cm}\begin{align*}
u(D,W)&=DW\\
MU_D&=W\\
MU_W&=D\\
\end{align*}\vspace{-0.5cm}
Write an equation for your *marginal rate of substitution* between $D$ and $W$.  (3 points)

c. Calculate the *optimum* quantities of $D$ and $W$ that maximizes your utility subject to your constraints. Plot this point on the first graph below, (call it point **A**), and sketch an indifference curve through that point. (10 points)

d. How much utility do you earn from the optimum bundle (point **A**)? (1 point)

e. Now suppose the price of Drinks ($D$) *rises* to \$4.00. Find the equation of the *new budget constraint* (in *graphable* form), and add it to the first graph below. (3 points)

f. Calculate the *new optimum* quantities of $x$ and $y$ under this new price. Plot this point on the first graph below, (call it point **B**), and sketch an indifference curve through that point. Hint: the formula for MRS has not changed. (6 points)

g. How much utility do you earn from the new optimum bundle (point **B**)? (1 point)

h. Plot the optima from parts c and f on the *second* graph below, describing the relationship between the price of Drinks and the optimal consumption of Drinks. Connect the points. What did you just draw? (3 points)

\begin{figure}[h!]
	\centering 
			\begin{tikzpicture}[scale=0.9] 
	\begin{axis}[%clip=false,
		axis lines=middle, 
		enlarge x limits={rel=0.1, upper},
		enlarge y limits={rel=0.1, upper},
		every axis y label/.style={at={(axis description cs:-0.2,0.5)},rotate=90,anchor=north},
		every axis x label/.style={at={(axis description cs:0.5,-0.1)},anchor=north},
	%legend pos=outer north east,
	xlabel=Drinks ($D$),
	ylabel=Wings ($W$),
	shader=flat,
	xtick={0,5,...,50},
	ytick={0,5,...,50},
	grid=major,
	ymin=0,
	xmin=0,
	ymax=50,
	xmax=50,
]
	\addplot[very thick, color=blue, domain=0:6, opacity=0]{x};
\end{axis}
\end{tikzpicture}
		\begin{tikzpicture}[scale=0.9] 
	\begin{axis}[%clip=false,
		axis lines=middle, 
		enlarge x limits={rel=0.1, upper},
		enlarge y limits={rel=0.1, upper},
		every axis y label/.style={at={(axis description cs:-0.2,0.5)},rotate=90,anchor=north},
		every axis x label/.style={at={(axis description cs:0.5,-0.1)},anchor=north},
	%legend pos=outer north east,
	xlabel=Drinks ($D$),
	ylabel=Price per Drink ($p_D$),
	shader=flat,
	xtick={0,5,...,50},
	ytick={0,1,...,5},
	grid=major,
	ymin=0,
	xmin=0,
	ymax=5,
	xmax=50,
]
	\addplot[very thick, color=blue, domain=0:6, opacity=0]{x};
\end{axis}
\end{tikzpicture}
\end{figure}

\clearpage 

\newpage
\thispagestyle{plain}
\mbox{}
\clearpage 

## Long Answer (10 points each)

Choose any \textbf{two (2)} of the following questions to answer. Please answer clearly and concisely (2-5 sentences is sufficient). If applicable, show all work and clearly label all graphs.

12. As you are taking this exam, you are implicitly solving a constrained optimization problem. Briefly explain what your objective is, what your constraint is, and what choices and tradeoffs you must make to attain this objective. \emph{Be specific}, in the context of taking an exam (meaning, we're not talking about utility and dollars, etc). 

13. Explain the difference between the *income effect* and the *real income effect.* Use an example of an *inferior* good in describing each effect. 

14. Suppose someone argues that although a hurricane hitting an area is a terrible tragedy, it is an economic blessing in disguise. After a hurricane has ravaged an area, all of the homes and businesses need to be rebuilt. This will create new demand for construction, homebuilding, and restocking the stores in the area, which will lead to new jobs to help with the rebuilding and restoring all of the businesses in the area. All of this will stimulate the economy and create jobs in a way that would not happen had it not been for the hurricane. Respond to this argument.
 

\newpage
\thispagestyle{plain}
\mbox{}
\clearpage 

## Formulas

$$p_xX+p_yY=m$$

$$\epsilon_{q,p}=\frac{1}{slope}\times \frac{p}{q}$$

$$\epsilon_{q,m}=\frac{\% \Delta q}{\% \Delta m}$$

$$\epsilon_{q_x,p_y}=\frac{\% \Delta q_x}{\% \Delta p_y}$$

- Two curves are *tangent* at a point $\iff$ two curves have the same slope *at that point*