---
title: "2.1 Theory of the Firm - Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

# Overview

Today we start looking on the supply side of the market for the next few weeks. You will ultimately see, we will use the same tools (and get basically the same results!) for studying producers (constrained optimization models) as we did for consumers. Sometimes, these models finally "click" for students the second time around, and production is often more intuitive than utility and consumption.

Today we set up the problem, and discuss what it is that firms do. If you want to learn a lot more about the economics of organization and the firm, take my Industrial Organization class next semester.

# Slides

- [<i class="fas fa-external-link-square-alt"></i> Lecture Slides](/slides/10-slides.html)

# Appendix

## Solving the Firm's Problem in One Step

Traditionally, it is easier if we break the firm's profit maximization problem into two stages: 

1. The firm's **profit maximization problem**:
  - <span color="blue">**Choose**: $<$ Output: $q$ $>$</span>
  - <span color="green">**To Maximize**: $<$ Profit: $\pi=pq-C(q)$ $>$</span>
  - written mathematically:
  $$\max_{\textcolor{blue}{q \geq 0}}\textcolor{green}{pq-C(q)}$$
2. The firm's **cost minimization problem**:
  - <span color="blue">**Choose**: $<$ Inputs: $l,k$ $>$</span>
  - <span color="green">**To Minimize**: $<$ Total cost: $C(q)=wl+rk$ $>$</span>
  - <span color="red">**Subject to**: $<$ Producing optimal output: $q^*=f(k,l)$ $>$</span>
  - written mathematically:
  $$\min_{\textcolor{blue}{l,k \geq 0}}\textcolor{green}{pq-C(q)}$$
  $$\textcolor{red}{s.t. y^*=f(k,l)}$$

We proceed in class with the second stage first, and then the first stage. However, this appendix shows that the problem can be solved in a *single stage.* For simplicity, we look at the short run, where there is a single input $l$ that can be chosen $(\bar{k}$ is fixed). 

The firm's **profit maximization problem**:
  - <span color="blue">**Choose**: $<$ Input and Output: $l,y$ $>$</span>
  - <span color="green">**To Maximize**: $<$ Profit: $\pi=py-wl$ $>$</span>
  - <span color="red">**Subject to**: $<$ Technology: $q=f(\bar{k},l)$ $>$</span>
  - Written mathematically:
  $$\max_{\textcolor{blue}{l,y \geq 0}}\textcolor{green}{pq-wl}$$
  $$\textcolor{red}{s.t. y=f(\bar{k},l)}$$


