---
title: "4.2: Consequences and Sources of Monopoly - Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

# Overview

Today we continue our look at monopoly.

# Slides

- [<i class="fas fa-external-link-square-alt"></i> Lecture Slides](/slides/21-slides.html)

# Practice Problems

Today may finish working on last class' [practice problems](/practice/20-practice). Answers will be posted later.

# Exam 2 Corrections

Exam 2 corrections are due Monday November 25 for Section 2 (M/W) and Tuesday November 26 for Section 1 (Tu/Th). Please turn in your corrections and your original exam.

# Problem Set 5 Due Mon/Tues Dec 2/3

[Problem Set 5](/assignments/05-problem-set) on Equilibrium (3.1-3.3) is posted and will be due on Monday/Tuesday December 2/3 by section (M/W vs. Tu/Th).

This will be your **final graded homework** of the semester. A reminder, the homework grade (20% of course grade) is the *average* of your homework grades. Again, see the [grade calculator](https://ryansafner.shinyapps.io/306_grade_calculator/) or the [syllabus](/syllabus) to estimate how this impacts your overall grade.

I will give a "homework" (with answers, of course) on Unit 4 which we are currently covering, so that you can practice for the Final exam, but I will not collect or grade it.