---
title: "Opinion-Editorial Assignment"
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(pander)
source(file.path(here::here(), "lib", "graphics.R"))
```

*Due by the last day of class*

- [<i class="fas fa-external-link-square-alt"></i> How to Write Well](/slides/paper-slides.html)
- See examples of good student Op-eds on Blackboard (Course Documents)

> "How can I know what I think until I see what I say?" --- E. M. Forster on Writing


# Overview 

Your task is to write an Opinion-Editorial (Op-ed) piece that applies the economic way of thinking to some public policy-relevant issue. An op-ed is a newspaper article that expresses the opinions of a writer who is unaffiliated with the newspaper or its editorial board. Often, the writer of an op-ed has no journalism experience, or (as you will soon discover), little understanding of economics. Thus, you are at no disadvantage as a student just beginning your experience with economics and writing! To get an idea, look at any newspaper's "Opinion" section on their website or in print.

The purpose of this assignment is fourfold: (1) to demonstrate to you that economics is a wonderful way of thinking about any social issue, (2) for you to demonstrate to me that you have mastered the material of this course, (3) to develop your writing and argumentative skills, and (4) to help you develop, change, and/or strengthen your own views by grappling with them in writing.

In general, am looking for a short paper that puts forth an argument and defends it. You should be able to summarize your position in one sentence -- the thesis of your paper that you will argue for. It should be a reasonably original argument (it is difficult with limited knowledge to offer something truly original), and it should be your own take on the topic. It should use some principle(s) or insight(s) from (micro) economics to bolster your conclusions.

Please note that, while you are not required to, I highly recommend discussing your ideas with me over email or in person. I will also read any drafts you would like to submit to me early, and provide you with helpful comments, subject to my own availability. Both to disincentivize procrastination, and because I have no time to read 100 papers right before the end of class, **I will stop reading and commenting on drafts after November 30.**

If you publish your op-ed in any media outlet (newspapers, news websites, major blogs) by the end of the semester, you will earn extra credit according to the following scale:^[Note: *Websites like reddit, Buzzfeed, or personal blogs that do not require professional editorial approval do __not__ count!*]

| Publication | Examples | Points |
|-------------|----------|--------|
| Hood-affiliated outlet | *The Blue and Grey*, Professors' blogs | 10 |
| Local/regional Newspaper | *Frederick News-Post* | 20 |
| National Newspaper/blog | *NY Times, WaPo, WSJ, USA Today, HuffPo* | 40 |

*Meeting the market test is what matters most!*  

**Your Op-Ed, with a word count, is due by the last day of class, via email, and constitutes 20\% of your final course grade.**

# Length, References, & Mechanics

The goal of any op-ed is to convince reasonably-educated readers of some particular conclusion (also known as a *thesis*). This conclusion is of course, the opinion of the author, but this opinion must be backed by theory and evidence that leads reasonable people to agree with that conclusion. The claim you make as your conclusion should be relevant, debatable, testable, and provide new insight on a topic. Telling the reader *"people who do not recycle are selfish"* is neither informative nor persuasive, but telling the reader *"recycling reduces the amount of trash going into local landfills by X tons a year"* is at least informative, if not also persuasive. **You are free to take any position on any issue that you choose, so long as it is backed by evidence and sound use of the economic way of thinking.** For more details, see my presentation slides linked above. 

I always hesitate to give formal length requirements, because most students will write the bare minimum, and also because different papers have different optimal lengths. What truly matters is that your paper is long enough to say what you need to say, to say it well, and to say it briefly. Ceterus paribus, if papers A and B say the same thing, but paper B says it in half the length (without sacrificing key arguments), paper B is a better paper. In any event, this assignment will largely follow the style of most major newspapers. **Your op-ed must be between 500 and 1000 words. You must include a word count with your final copy.** There are no other formal requirements but, I recommend formatting it in 12 point Times New Roman or Arial font, double spaced, just to make it easier for me to read (and nearly every other paper you write will ask for this).

While this is not a research paper, I do want you to include some scholarly sources -- for example, if you cite the work of an economist on the issue, or if you use statistics, data, or facts (which you should!). While newspapers do not publish a bibliography for each op-ed, they will scrutinize every empirical claim and ask the author for sources to back it up. **Thus, I would like a list of sources you used for your article, and expect you to have at least 1-3, depending on your topic and argument.** I am not particularly picky about exactly how you format this list, just please be consistent. Look at my slides or my handouts for a suggested style.

# Suggested Topics

Remember that economics is a way of analyzing the world, rather than a narrow domain of topics for studying. Thus, while you may certainly write about the typical "mundane" topics of economics we often think about (money, monopoly, inflation, etc), I strongly encourage you to apply economics to something you find much more interesting about the world - from corruption in FIFA, to the constitutional political economy of pirates, to bitcoin displacing currencies, to the illegal downloading of Game of Thrones, to the cultural institutions of the Jersey Shore, to the monopoly power of the WWE in wrestling, to the relationship of Uber & Airbnb to taxis and hotels, to the privatization of asteroids, to the economics of crowdfunding, to drugs, sex, and rock n roll. In fact, it is often those topics that are most eccentric and "out in left field" that make the best op-eds! 

There are plenty of issues around us, both immediate and visible (racism and policing, college costs, ISIS, planned parenthood, gun control, etc) and latent long term issues (monetary policy and interest rates, the drug war, government spending and debt, science funding, etc).

The scope of topics allowed for your paper is anything that uses the economic way of thinking to make some sort of conclusion. This is an extremely wide scope, but here are a few main types of op-eds that will tend to result from this, along with some great examples of op-eds that use economics to reach an interesting or provocative conclusion. 

1. Taking a stand on a position, either actively being discussed in the news, or a long-standing underlying issue

- [The Case for Getting Rid of Borders - Completely (*The Atlantic*)](http://www.theatlantic.com/business/archive/2015/10/get-rid-borders-completely/409501/)
- [The Racial Reality of Policing (*Wall Street Journal*)](http://www.wsj.com/articles/the-racial-reality-of-policing-144139098)
- [Zoning Out the Poor (*Washington Post*)](https://www.washingtonpost.com/news/volokh-conspiracy/wp/2015/07/26/zoning-out-the-poor/)
- [This Child Doesn't Need a Solar Panel (*Wall Street Journal*)](http://www.wsj.com/articles/this-child-doesnt-need-a-solar-panel-1445466967)
- [How to Save Detroit (*Wall Street Journal*)](http://www.wsj.com/news/articles/SB10001424052702303848104579308612337146296)
- [In an Uber World, Fortune Favors the Freelancer (*New York Times*)](http://www.nytimes.com/2015/06/28/upshot/in-an-uber-world-fortune-favors-the-freelancer.html)
- [What the West Gets Wrong About Russia (*New York Times*)](http://www.nytimes.com/2015/08/13/opinion/what-the-west-gets-wrong-about-russia.html)

2. Criticizing recent statements, current popular fallacies, or policy proposals of others in the news

- [Shut Up Royal Baby Haters, Monarchy is Awesome (*Washington Post*)](http://www.washingtonpost.com/news/wonkblog/wp/2013/07/23/shut-up-royal-baby-haters-monarchy-is-awesome/)
- [Trump's Protectionist Fallacies Have Been Refuted By Free Market Economists for Hundreds of Years (*Huffington Post*)](http://www.huffingtonpost.com/tom-mullen/trumps-protectionist-fall_b_8056400.html)
- [Trump's Exploits Rational Ignorance (*USA Today*)](http://www.usatoday.com/story/opinion/2015/10/04/trump-polls-immigration-taxes-column/72755896/)
- [Bernie Sanders on Immigrants: Silly, Tribal and Economically Illiterate (*Newsweek*)](http://www.newsweek.com/bernie-sanders-immigrants-silly-tribal-and-economically-illiterate-358369)
- [The Myth of a Stagnant Middle Class (*Wall Street Journal*)](http://www.wsj.com/news/articles/SB10001424127887323468604578249723138161566)
- [The '77 cents on the Dollar' Myth About Women's Pay (*Wall Street Journal*)](http://www.wsj.com/news/articles/SB10001424052702303532704579483752909957472)
- [How Everyone Gets the Sharing Economy Wrong (*Wall Street Journal*)](http://www.wsj.com/articles/how-everyone-gets-the-sharing-economy-wrong-1432495921)
- [Why Bill Gates Hates my Book (*Wall Street Journal*)](http://www.wsj.com/news/articles/SB120235183917849631)
- [In Zimbabwe, We Don't Cry for Lions (*New York Times*)](http://www.nytimes.com/2015/08/05/opinion/in-zimbabwe-we-dont-cry-for-lions.html)

3. Providing new insight into a social phenomenon that is interesting or novel, designed to get people talking

- [Driven to Kill: Why Drivers in China Intentionally Kill the Pedestrians they Hit (*Slate*)](http://www.slate.com/articles/news_and_politics/foreigners/2015/09/why_drivers_in_china_intentionally_kill_the_pedestrians_they_hit_china_s.html)
- [The Case for the City-State (*Wall Street Journal*)](http://www.wsj.com/articles/SB10001424052702303919504577522641691745740)
- [What Hollywood Can Teach Us About the Future of Work (*New York Times*)](http://www.nytimes.com/2015/05/10/magazine/what-hollywood-can-teach-us-about-the-future-of-work.html)
- [Losing is Good for You (*New York Times*)](http://www.nytimes.com/2013/09/25/opinion/losing-is-good-for-you.html)
- [The $250 Econ 101 Textbook (*Wall Street Journal*)](http://www.wsj.com/articles/craig-richardson-the-250-econ-101-textbook-1421192341)
- [Cash for Kidneys: The Case for a Market for Organs (*Wall Street Journal*)](http://www.wsj.com/news/articles/SB10001424052702304149404579322560004817176)
- [The Bitcoin Schism Shows the Genius of Open Source (*Wired*)](http://www.wired.com/2015/08/bitcoin-schism-shows-genius-open-source/)
- [Should Physician Pay Be Tied to Performance? (*Wall Street Journal*)](http://www.wsj.com/articles/SB10001424127887323528404578454432476458370)

# Sources for Inspiration

Here is a list of a few places you might consider to dig up some information on your topic, or to help you find a topic. Just be sure to read and cite the actual sources that these secondary sources cite. 

- Major news outlets (e.g. CNN, Wall Street Journal, New York Times, USA Today, Huffington Post, the Guardian) and wherever you may find your news (e.g. reddit, Buzzfeed, etc) both for current events, and also their Opinion/Commentary sections for other op-eds to learn from and/or critique
- Wikipedia -- no seriously, it is the first place I go to learn about a new topic. Just be sure to actually investigate the underlying research and use that for your references!
- Economics Podcasts
    - [Econtalk](http://econtalk.org) -- a fantastic podcast series by Russ Roberts that interviews famous economists, philosophers, businesspeople, and other figures who have an impact on the world of ideas	
    - [Freakonomics (Radio)](http://freakonomics.com/) -- another great podcast by one of the authors of the famed *Freakonomics* books about intermediate-level economic topics, often an in-depth series of interviews on a major issue 
    - [NPR Planet Money](http://npr.org/sections/money) -- another good podcast series on economics topics and current events, much shorter and more 10,000-foot level approach than Econtalk or Freakonomics
- Popular Economists' Blogs/Blogs on Economics:
    - [Marginal Revolution](http://marginalrevolution.com) -- Tyler Cowen & Alex Tabarrok (head and shoulders above the rest!)
    - [Cafe Hayek](http://cafehayek.org) -- Don Boudreaux (libertarian-leaning, mostly just Don on trade and micro-policy)
    - [EconLog](http://econlog.org) -- Bryan Caplan, David Henderson (libertarian-leaning, good analysis)
    - [The Conscience of a Liberal](http://krugman.blogs.nytimes.com/) -- Paul Krugman at New York Times (strong left-wing politics)
    - [The Grumpy Economist](https://johnhcochrane.blogspot.com/) -- John Cochrane (Chicago School approach)
    - [Greg Mankiw's Blog](http://gregmankiw.blogspot.com) -- Greg Mankiw (moderate conservative, New Keynesian approach)
    - [Undercover Economist](http://timharford.com/articles/undercovereconomist/) -- Tim Harford (British, non-political, very easy to understand)
    - [Chris Blattman](https://chrisblattman.com/) -- Chris Blattman (great on economic development, poverty, and conflict in poor countries)
    - [Slate Star Codex](http://slatestarcodex.com) -- "Scott Alexander" (a pseudonym, apparently a Medical Student, but one of the most lucid social science blogs ever written)
    - [Fivethirtyeight](https://fivethirtyeight.com/) -- Nate Silver & co. (a journalist, but a *leader* on using data and statistics in social science and journalism)
    - [Andrew Gelman](http://andrewgelman.com) -- Andrew Gelman (a statistician, but another *leader* on using data and statistics for social science)

# Grading Rubric and Deadlines

Here is the rubric that I will use to grade your paper:


| Category | Points |
|----------|-------:|
| Persuasiveness | 30 |
| Soundness | 30 |
| Clarity | 20 |
| Organization | 10 |
| References | 5 |
| Style | 5 |
| TOTAL | 100 |

- **Persuasiveness**: How persuasive is your argument? Would a reasonably educated college-level reader who is familiar with economics and statistics but not necessarily this course find themselves understanding your argument and agreeing with you? [Write for an audience wider than just members of this class. Therefore, don't use terms, sources, or "inside jokes" that only other students in this class (and no one else) would understand.] Remember, your goal is not to convince *me* (though you may), your goal is to convince *any educated reader*, and I grade you the probability that this is likely. You are the lawyer, I am the judge, and your audience is the jury.
- **Soundness**: Are your theories consistent and logical, and did you apply them correctly? Did you choose relevant (and non-cherry picked) evidence to back it up? Are your facts, data, or case studies accurate?
- **Clarity** How clear is your paper? Is it clear what your research question is, how you answer it, and what your results are? Can you summarize these in a sentence or two? Are there confusing passages, excessive jargon or passive voice, or irrelevant arguments and examples?
- **Organization:** Is your paper organized? Have you presented your separate arguments/examples in a logical order? Is it clear when you are moving on from one section to another? Is it clear when and where you are summarizing and concluding?
- **References:** Does your paper use multiple reputable references? Does it properly cite them in the text for main ideas borrowed and for direct quotations? Are they consistently listed at the end in a references section?
- **Style:** Is your paper interesting and easy to read? Does it engage the reader? Is it written in active voice? This is somewhat subjective, and hence, the smallest portion of your grade.